# Generated by Django 6.0.7 on 2026-08-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_category_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('license_number', models.CharField(max_length=30)),
                ('assigned_orders', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Offline', 'Offline')], default='Offline', max_length=20)),
            ],
        ),
    ]
